#include <linux/userfaultfd.h>
#include <sys/ioctl.h>
#include <fcntl.h>

const long int _T_UFFD_API = UFFD_API;
#undef UFFD_API

const long int _T_UFFDIO_API = UFFDIO_API;
#undef UFFDIO_API

const long int _T_UFFDIO_REGISTER = UFFDIO_REGISTER;
#undef UFFDIO_REGISTER

const long int _T_UFFDIO_UNREGISTER = UFFDIO_UNREGISTER;
#undef UFFDIO_UNREGISTER

const long int _T_UFFDIO_WAKE = UFFDIO_WAKE;
#undef UFFDIO_WAKE

const long int _T_UFFDIO_COPY = UFFDIO_COPY;
#undef UFFDIO_COPY

const long int _T_UFFDIO_ZEROPAGE = UFFDIO_ZEROPAGE;
#undef UFFDIO_ZEROPAGE

const long int _T_UFFDIO_REGISTER_MODE_MISSING = UFFDIO_REGISTER_MODE_MISSING;
#undef UFFDIO_REGISTER_MODE_MISSING

const long int _T_UFFDIO_REGISTER_MODE_WP = UFFDIO_REGISTER_MODE_WP;
#undef UFFDIO_REGISTER_MODE_WP

const long int _T_UFFDIO_COPY_MODE_DONTWAKE = UFFDIO_COPY_MODE_DONTWAKE;
#undef UFFDIO_COPY_MODE_DONTWAKE

const long int _T_UFFDIO_ZEROPAGE_MODE_DONTWAKE = UFFDIO_ZEROPAGE_MODE_DONTWAKE;
#undef UFFDIO_ZEROPAGE_MODE_DONTWAKE

const long int _T_UFFD_API_IOCTLS = UFFD_API_IOCTLS;
#undef UFFD_API_IOCTLS

const long int _T_UFFD_API_RANGE_IOCTLS = UFFD_API_RANGE_IOCTLS;
#undef UFFD_API_RANGE_IOCTLS

const long int _T_UFFD_API_RANGE_IOCTLS_BASIC = UFFD_API_RANGE_IOCTLS_BASIC;
#undef UFFD_API_RANGE_IOCTLS_BASIC
